In [28]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

In [33]:
patch_size = 3

img = np.random.rand(6, 6, 3)
print(img)

[[[0.018 0.23  0.642]
  [0.446 0.884 0.341]
  [0.007 0.132 0.73 ]
  [0.686 0.638 0.993]
  [0.701 0.766 0.999]
  [0.749 0.196 0.313]]

 [[0.762 0.633 0.019]
  [0.031 0.539 0.743]
  [0.87  0.009 0.807]
  [0.44  0.104 0.446]
  [0.085 0.816 0.822]
  [0.709 0.156 0.158]]

 [[0.905 0.436 0.513]
  [0.457 0.264 0.064]
  [0.661 0.516 0.076]
  [0.594 0.973 0.805]
  [0.341 0.099 0.331]
  [0.023 0.901 0.37 ]]

 [[0.776 0.08  0.357]
  [0.227 0.651 0.369]
  [0.956 0.762 0.782]
  [0.201 0.132 0.555]
  [0.16  0.286 0.479]
  [0.011 0.675 0.389]]

 [[0.127 0.387 0.23 ]
  [0.215 0.852 0.848]
  [0.317 0.191 0.833]
  [0.826 0.336 0.338]
  [0.555 0.995 0.361]
  [0.361 0.241 0.364]]

 [[0.469 0.965 0.498]
  [0.446 0.367 0.378]
  [0.35  0.699 0.177]
  [0.307 0.587 0.903]
  [0.565 0.491 0.058]
  [0.099 0.835 0.829]]]


In [34]:
def find_vector_set(img, patch_size):
    dims = img.shape
    vector_set = np.zeros((dims[0]*dims[1], 3 * patch_size**2))
    offset = patch_size//2
    
    for i in range(offset, dims[0] - offset - 1) :
        for j in range(offset, dims[1] - offset - 1) :
            
            block = img[i - offset : i + offset + 1, j - offset : j + offset + 1, :]
            feature = block.ravel()
            vector_set[dims[0] * i + j, :] = feature
            
    mean_vec = np.mean(vector_set, axis = 0)
    vector_set = vector_set - mean_vec 
            
    return vector_set

In [35]:
vector_set = find_vector_set(img, patch_size)

In [15]:
import sklearn

In [36]:
from sklearn.decomposition import PCA
 
pca = PCA()
pca.fit(vector_set)
EVS = pca.components_
importance = pca.explained_variance_ratio_

In [37]:
importance

array([0.682, 0.076, 0.071, 0.047, 0.041, 0.029, 0.024, 0.017, 0.014,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
pca.explained_variance_ratio_ * 100

array([68.156,  7.552,  7.093,  4.738,  4.135,  2.862,  2.394,  1.672,
        1.399,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ])

In [39]:
EVS

array([[ 0.178,  0.156,  0.169,  0.182,  0.175,  0.221,  0.194,  0.18 ,
         0.263,  0.244,  0.165,  0.167,  0.195,  0.167,  0.2  ,  0.179,
         0.163,  0.219,  0.2  ,  0.179,  0.174,  0.193,  0.205,  0.205,
         0.199,  0.184,  0.197],
       [-0.129, -0.166,  0.282,  0.253, -0.207, -0.068, -0.021,  0.126,
        -0.119,  0.007, -0.248, -0.172,  0.012,  0.189, -0.116,  0.042,
         0.308,  0.216, -0.111,  0.207, -0.08 ,  0.009,  0.176,  0.323,
        -0.258, -0.432, -0.015],
       [ 0.082, -0.216,  0.07 ,  0.066,  0.015, -0.261, -0.247,  0.252,
         0.094, -0.085,  0.186, -0.214,  0.077,  0.339,  0.303, -0.04 ,
        -0.328, -0.006,  0.138,  0.242,  0.299, -0.148, -0.328,  0.002,
         0.   , -0.064, -0.159],
       [-0.197, -0.143,  0.147,  0.172,  0.379,  0.117, -0.266, -0.343,
        -0.108,  0.393,  0.064, -0.115, -0.406, -0.004, -0.047,  0.111,
         0.026,  0.159,  0.202, -0.062,  0.124,  0.123, -0.014, -0.114,
        -0.021,  0.004, -0.259],
    

In [ ]:
def clustering(FVS, dims, components):
    kmeans = KMeans(components, verbose = 0, random_state=123)
    kmeans.fit(FVS)
    output = kmeans.predict(FVS)
    #count  = Counter(output)
    
    labels= kmeans.labels_
    centroids = kmeans.cluster_centers_
    
    cluster_map = np.zeros((dims[1], dims[2]))
 
    for i in range(dims[1]) :
        for j in range(dims[2]) :
            cluster_map[i, j] = output[dims[2]*i+j]
                    
    return cluster_map, labels, centroids

In [52]:
mask = np.array([[1, 1, 1], [1, 1, 0], [0, 0, 0]])
patch = img[:3, :3, :]
patch[mask == 0] = 0
print(patch)
patch_vec = patch.ravel()
np.dot(patch_vec, EVS)

[[[0.018 0.23  0.642]
  [0.446 0.884 0.341]
  [0.007 0.132 0.73 ]]

 [[0.762 0.633 0.019]
  [0.031 0.539 0.743]
  [0.    0.    0.   ]]

 [[0.    0.    0.   ]
  [0.    0.    0.   ]
  [0.    0.    0.   ]]]


array([ 0.201, -0.218, -0.641,  0.249, -0.073,  0.128, -0.766, -0.292,
       -0.215,  0.104,  0.079, -0.431, -0.372,  0.628, -0.226,  0.245,
       -0.064,  0.207,  0.173,  0.095,  0.46 , -0.401, -0.284,  0.777,
        0.718, -0.285,  0.219])

In [53]:
patch_vec

array([0.018, 0.23 , 0.642, 0.446, 0.884, 0.341, 0.007, 0.132, 0.73 ,
       0.762, 0.633, 0.019, 0.031, 0.539, 0.743, 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])